name: rastah
description: "Urdu AI Therapist for Pakistani Students - Your companion for listening and understanding"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.6.1              # Navigation between screens
  flutter_svg: ^2.0.10            # For SVG icons and illustrations
  
  # State Management
  provider: ^6.1.2                # For managing app state
  
  # Local Storage
  shared_preferences: ^2.3.3      # Store user profile & settings locally
  
  # HTTP & API
  http: ^1.2.2                    # For OpenAI API calls (easily replaceable)
  dio: ^5.7.0                     # Alternative HTTP client for advanced features
  
  # Voice Functionality
  flutter_tts: ^4.2.0             # Text-to-Speech (Urdu support)
  speech_to_text: ^7.0.0          # Speech-to-Text for voice input
  permission_handler: ^11.3.1     # Handle microphone permissions
  
  # Media & Files
  image_picker: ^1.1.2            # For profile pictures
  url_launcher: ^6.3.2            # Launch URLs and external apps
  
  # Charts & Data Visualization
  fl_chart: ^1.0.0               # For mood tracking chart
  
  # Animations & UI Enhancement
  animated_text_kit: ^4.2.2       # Animated text for welcome screens
  shimmer: ^3.0.0                 # Loading animations
  lottie: ^3.1.2                  # Beautiful animations (optional)
  
  # Urdu Text & Internationalization
  intl: ^0.19.0                   # Date formatting and localization
  google_fonts: ^6.2.1            # Easy access to all Google Fonts
  
  # Additional UI Components
  flutter_slidable: ^3.1.1        # Swipe actions (if needed)
  flutter_spinkit: ^5.2.1         # Loading indicators

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets for images, icons, and illustrations
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/

  # Note: Using Google Fonts instead of local fonts for easier setup